### ISSUE TITLE
Missing function in utils2

### ISSUE THREAD

**Issue by harisont** [sdobnik/computational-semantics#3]
When I try to run the first cell of [problem-set-2-part3.ipynb](https://github.com/sdobnik/computational-semantics/blob/master/problem-set-2/problem-set-2-part3.ipynb) I get the following error:
```
ImportError: cannot import name 'compare_synsem' from 'utils2' (/run/media/harisont/0684-7E46/Sverige/Uni/Courses/Year 2/Semester 2/Trimester 2/Computational semantics/lt2213-lab-2-group-6/harisont/utils2.py)
```
and `compare_synsem` is in fact not defined in [utils2.py](https://github.com/sdobnik/computational-semantics/blob/master/problem-set-2/utils2.py) but it is necessary to run other cells later on in the notebook.

**Comment by mmehdig** [comment]
Thanks for the report. I pushed the missing change.
