### ISSUE TITLE
not a proper call for function in the VG part or variable misnaming 

### ISSUE THREAD

**Issue by gusmakali** [sdobnik/computational-semantics#4]
Regarding VG part 3a, 3b. 

I corrected the following in my notebook but probably the notebook should be updated as well. 

there is a `grammar`variable defined: 

```python
grammar = FeatureGrammar(
    syntax.start(),
    syntax.productions() + \
    FeatureGrammar.fromstring(fcfg_storage_answers_a).productions() + \
    FeatureGrammar.fromstring(fcfg_storage_answers_b).productions()
)
```

then the defined variable `grammar` is not used. instead in the next calling of `sem_parser` the variable `new_syntax` is used, which was defined way earlier with a different grammar. I'm talking about the following line:

```
sents_reps = sem_parser(sentences, new_syntax, verbose=False) # shouldn't it also be is_cs=True?
```

the part below would never run in an expected way 

```python
for i, (sent, semreps) in enumerate(sents_reps.items()):
    for semrep in semreps:
        display_translation(f"{i}. {sent}", semrep)
```

Also, as far as I understand part3 should be implemented with Cooper Storage as the extension of  grammar from part2. However, the above `for` loop combines CS grammar defined by me with not CS grammar from `utils2` by calling `syntax.productions()`.

**Comment by mmehdig** [comment]
Thanks for the report. 

In this question, you are supposed to extend the grammar you had in part2. We didn't have your grammar that was why some part of the code is missing. You are absolutely right, `syntax` doesn't have cooper storage and it shouldn't be used as an answer here. You should ignore the lines using the non-CS grammar and change them based on how you treat results from cooper storage parser in part2 (we have a flag for cooper storage in sem_parser). 

I am not going to change the code at this point assuming that you can figure out how to use the grammar on part2 here. But I can help with more clarification on how to solve it.

**Comment by mmehdig** [comment]
I am not going to close this issue so if more clarification is needed we can provide it here too.

**Comment by sdobnik** [comment]
We have now added the basic storage grammar to util2.py which can be accessed as ´syntax_storage´ and also adjusted code so that it uses this grammar.
